let items



try {
    items.forEach(item => {
        console.log(item)
    });
} catch (error) {
    console.log(error)
}
console.log("Try - Catch is working...")